# Generated by Django 5.0.2 on 2026-05-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar_api', '0003_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Tiempo Completo', 'Tiempo Completo'), ('Medio Tiempo', 'Medio Tiempo'), ('Hora-Clase', 'Hora-Clase')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='grado_academico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Prefiero no decirlo', 'Prefiero no decirlo')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='campus',
            field=models.CharField(blank=True, choices=[('CU San Manuel', 'CU San Manuel'), ('CU2', 'CU2')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='sueldo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
